# Generated by Django 6.0.4 on 2026-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/'),
        ),
    ]
